[build]
  command = "npm run build"
  publish = "dist"

# Redirects all routes to index.html for single-page application
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Cache control for static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
